=== modeverv/AS_proj/tutorial_sample/XML_viewer/src/assets/UserManual.dtd
<!--DTD for Product. Typically invoked by
      <!DOCTYPE  Product  SYSTEM
    "F:/Demo/LaSxml/UserManual.dtd">
-->


<!ELEMENT Product    (Para*, Model+, Troubleshooting) >
<!ATTLIST Product    ProductGroup  (Sunglasses)  #REQUIRED
                     BrandName     CDATA         #REQUIRED
                     Number        CDATA       #REQUIRED >

<!ELEMENT Action     (Para+, RelatedTopics?) >

<!ELEMENT Address    (#PCDATA) >

<!ELEMENT Availability (Para+) >

<!ELEMENT Caution    (Para+) >

<!ELEMENT Cleaning   (Para+, Steps+, Note?) >

<!ELEMENT Company    (#PCDATA) >

<!ELEMENT Compliance (Para+) >

<!ELEMENT Concern    (Para+) >

<!ELEMENT Description (Para+) >

<!ELEMENT Distribution (Distributor+) >

<!ELEMENT Distributor (Territory, Company, Address) >

<!ELEMENT Feature    (Para+) >

<!ELEMENT Features   (Para*, Feature+) >

<!ELEMENT Graphic    EMPTY >
<!ATTLIST Graphic    file      CDATA     #IMPLIED
                     dpi       NMTOKEN   #IMPLIED
                     alt       CDATA     #IMPLIED
                     impsize   CDATA     #IMPLIED
                     impby     (ref|copy)  #IMPLIED
                     sideways  NMTOKEN   #IMPLIED
                     impang    CDATA     #IMPLIED
                     xoffset   CDATA     #IMPLIED
                     yoffset   CDATA     #IMPLIED
                     position  NMTOKEN   #IMPLIED
                     align     NMTOKEN   #IMPLIED
                     cropped   NMTOKEN   #IMPLIED
                     float     NMTOKEN   #IMPLIED
                     width     CDATA     #IMPLIED
                     height    CDATA     #IMPLIED
                     angle     CDATA     #IMPLIED
                     bloffset  CDATA     #IMPLIED
                     nsoffset  CDATA     #IMPLIED >

<!ELEMENT Issue      (Title, Concern, Action) >
<!ATTLIST Issue      Product   (Sunglasses|Boots)  #REQUIRED
                     Category  (Usage|Repair|Cleaning|Maintenance)  #REQUIRED
                     ReturnToFactory  (Yes|No)  #REQUIRED
                     Warranty  (Yes|No)  #REQUIRED >

<!ELEMENT Model      (Name, Picture, Description, Features, Usage,
                              Operation, Cleaning, Storage, Availability,
                              Parts, Warranty, Distribution, Compliance,
                              Notes, TroubleshootingLink) >
<!ATTLIST Model      ModelNumber  CDATA     #REQUIRED
                     Id        ID        #IMPLIED
                     Season    (Fall|Winter|Summer|Spring)  #REQUIRED >

<!ELEMENT Name       (#PCDATA) >

<!ELEMENT Note       (Para+) >

<!ELEMENT Notes      (Para, (Para | Caution | Warning)*) >

<!ELEMENT Operation  (Para*, Steps+) >

<!ELEMENT Para       (#PCDATA) >

<!ATTLIST Para       Id        ID        #IMPLIED >

<!ELEMENT PartName   (#PCDATA) >

<!ELEMENT PartNumber (#PCDATA) >

<!ELEMENT PartQuantity (#PCDATA) >

<!ELEMENT Parts      (Para*, PartsTable) >

<!ELEMENT PartsBody  (PartsRow+) >

<!ELEMENT PartsHeading (PartsRow) >

<!ELEMENT PartsRow   (PartNumber, PartName, PartQuantity) >

<!ELEMENT PartsTable (PartsHeading, PartsBody) >

<!ELEMENT Picture    (Graphic) >

<!ELEMENT RelatedTopic EMPTY >
<!ATTLIST RelatedTopic IdRef     IDREF     #REQUIRED
                       format    CDATA     #IMPLIED >

<!ELEMENT RelatedTopics 
                     (RelatedTopic) >

<!ELEMENT SectionLink EMPTY >
<!ATTLIST SectionLink IdRef     IDREF     #REQUIRED
                      format    CDATA     #IMPLIED >

<!ELEMENT Step       (Para?, (Warning | Caution)*, Graphic?)+ >

<!ELEMENT Steps      (Title, Step+, Note?) >

<!ELEMENT Storage    (Para, (Para | Note | Caution | Warning)*) >

<!ELEMENT Territory  (#PCDATA) >

<!ELEMENT Title      (#PCDATA) >

<!ELEMENT Troubleshooting (Para+, Issue+) >

<!ELEMENT TroubleshootingLink (SectionLink) >

<!ELEMENT Usage      (Para, (Para | Warning | Caution)*) >

<!ELEMENT UserManual (Product+) >
<!ATTLIST UserManual Language  (English|French|German)  #REQUIRED
                     Season    (Spring|Summer|Fall|Winter)  #REQUIRED
                     Year      NMTOKEN   #REQUIRED >

<!ELEMENT Warning    (Para+) >

<!ELEMENT Warranty   (Para) >

=== modeverv/AS_proj/tutorial_sample/XML_viewer/src/assets/UserGuide.xml
<?xml version="1.0" encoding="UTF-8"?> <!DOCTYPE UserManual SYSTEM "UserManual.dtd" [ <!-- Begin Document Specific Declarations -->  <!-- End Document Specific Declarations -->]><UserManual Language = "English" Season = "Summer" Year = "2008"> <Product ProductGroup = "Sunglasses" BrandName = "Slades" Number = "500"> <Para>Slades—the world’s leading sunglasses—featuring unparalleled style, comfort, and protection against the glare of the sun. There’s a style that’s right for you—from everyday needs to the demands of extreme sports</Para> <Model ModelNumber = "146 146 010" Id = "BABCHEHF" Season = "Summer"> <Name>XT007 Uptown Style</Name> <Picture> <Graphic file = "graphic1.swf" impsize = "1.597in 0.972in" impby = "ref" sideways = "0" impang = "0.000" xoffset = "0.019in" yoffset = "0.000in" position = "tleft" align = "aoutside" cropped = "0" float = "0" width = "1.635in" height = "0.972in" angle = "0.000" bloffset = "-0.819in" nsoffset = "-1.625in"/> </Picture> <Description> <Para>The XT007 Uptown Style is your best choice in sunglasses for everyday wear in the city, in the country, or on the road.</Para> </Description> <Features> <Feature><Para>Light-weight nylon frame</Para></Feature> <Feature><Para>Polycarbonate, anti-glare lenses</Para></Feature> <Feature><Para>Carry pouch/lens cloth included</Para></Feature> <Feature><Para>Interchangeable lens inserts sold separately</Para></Feature> <Feature><Para>Prescription lenses available through your eye care professional</Para></Feature> </Features> <Usage> <Para>Designed to reduce daylight dazzle in normal conditions while walking, driving, or viewing sporting events, for example. Lightweight, yet solid, construction makes this style suitable for use under normal, low-stress conditions. State-of-the-art technology provides unmatched comfort and protection from the glare of the sun.</Para> </Usage> <Operation> <Para>Changing the lenses is covered in this section.</Para> <Steps><Title>Changing the lenses:</Title> <Step><Para>Wash hands with mild detergent and dry with lint-free cloth.</Para></Step> <Step><Para>Hold glasses in one hand with lenses facing towards you.</Para><Graphic file = "graphic2.swf" impsize = "2.790in 1.156in" impby = "ref" sideways = "0" impang = "0.000" xoffset = "0.477in" yoffset = "0.012in" position = "below" align = "aleft" cropped = "0" float = "0" width = "3.682in" height = "1.189in" angle = "0.000" nsoffset = "0.000in"/></Step> <Step><Para>Grab right lens, and pull with a right and downward motion. Lens will begin to disengage from frame.</Para><Graphic file = "graphic3.swf" impsize = "2.790in 1.481in" impby = "ref" sideways = "0" impang = "0.000" xoffset = "0.508in" yoffset = "-0.003in" position = "below" align = "aleft" cropped = "0" float = "0" width = "3.703in" height = "1.490in" angle = "0.000" nsoffset = "0.000in"/></Step> <Step><Para>Continue holding lens, and pull with a left and downward motion until lens completely separates from frame.</Para><Graphic file = "graphic4.swf" impsize = "2.790in 1.408in" impby = "ref" sideways = "0" impang = "0.000" xoffset = "0.527in" yoffset = "-0.008in" position = "below" align = "aleft" cropped = "0" float = "0" width = "3.724in" height = "1.413in" angle = "0.000" nsoffset = "0.000in"/></Step> <Step><Para>Remove new lens from lens case and store old lens in its place.</Para></Step> <Step><Para>Align top left edge of lens with top left edge of frame.</Para><Graphic file = "graphic5.swf" impsize = "2.790in 1.408in" impby = "ref" sideways = "0" impang = "0.000" xoffset = "0.510in" yoffset = "-0.021in" position = "below" align = "aleft" cropped = "0" float = "0" width = "3.828in" height = "1.398in" angle = "0.000" nsoffset = "0.000in"/></Step> <Step><Para>Carefully fit lens into frame, and gently push lens with a left and upward motion.</Para> <Warning><Para>When inserting a lens into the frame, use light pressure. Forcing a lens can damage the lens and frame.</Para></Warning> <Graphic file = "graphic6.swf" impsize = "2.790in 1.408in" impby = "ref" sideways = "0" impang = "0.000" xoffset = "0.558in" yoffset = "0.004in" position = "below" align = "aleft" cropped = "0" float = "0" width = "3.787in" height = "1.438in" angle = "0.000" nsoffset = "0.000in"/></Step> <Step><Para>Continue placing pressure on the lens and push with a right and upward motion.</Para><Graphic file = "graphic7.swf" impsize = "2.790in 1.435in" impby = "ref" sideways = "0" impang = "0.000" xoffset = "0.527in" yoffset = "0.000in" position = "below" align = "aleft" cropped = "0" float = "0" width = "3.724in" height = "1.481in" angle = "0.000" nsoffset = "0.000in"/></Step><Step><Para>Continue to push lens into frame until completely engaged.</Para><Graphic file = "graphic8.swf" impsize = "2.790in 1.156in" impby = "ref" sideways = "0" impang = "0.000" xoffset = "0.548in" yoffset = "0.012in" position = "below" align = "aleft" cropped = "0" float = "0" width = "3.766in" height = "1.210in" angle = "0.000" nsoffset = "0.000in"/></Step><Step><Para>Repeat steps 2 through 9 with second lens, reversing directions.</Para></Step></Steps></Operation><Cleaning><Para>For the optimum performance of your sunglasses, clean them daily.</Para><Steps><Title>To clean your glasses:</Title><Step><Para>Rinse in warm water.</Para></Step><Step><Para>Use a mild liquid dish soap or non-abrasive glass detergent to wash each lens surface.</Para></Step><Step><Para>Dry with a clean, soft, absorbent cloth (no paper-based products).</Para></Step><Note><Para>Do not use paper-based products to clean your lenses. Do not use abrasive cleaners, soaps, or detergents; they will scratch the lens. Do not use tissues with added lotions, lanolin, silicone, or other cleaners; they will leave a film on the lens.</Para></Note></Steps></Cleaning><Storage><Para>Use the storage case provided with your glasses to safeguard the frame and lenses.</Para><Caution><Para>Excessive heat can cause damage to the frames and lenses. Avoid storing your sunglasses where direct heat is common, for example, on the dashboard of a car or on top of a radiator.</Para></Caution></Storage><Availability><Para>The XT007 Uptown Style is available in the U.S., Northern Europe, and Latin America.</Para></Availability><Parts><Para>Visit your local sunglasses retailer or optician for maintenance or to order optional accessories or replacement parts.</Para><PartsTable><PartsHeading><PartsRow><PartNumber>Part number</PartNumber><PartName>Description</PartName><PartQuantity>Quantity</PartQuantity></PartsRow></PartsHeading><PartsBody><PartsRow><PartNumber>45789-03</PartNumber><PartName>Frame</PartName><PartQuantity>1</PartQuantity></PartsRow><PartsRow><PartNumber>47550-23</PartNumber><PartName>Tinted lens—Left</PartName><PartQuantity>1</PartQuantity></PartsRow><PartsRow><PartNumber>47550-24</PartNumber><PartName>Tinted lens—Right</PartName><PartQuantity>1</PartQuantity></PartsRow><PartsRow><PartNumber>47551-23</PartNumber><PartName>Mirror lens—Left</PartName><PartQuantity>1</PartQuantity></PartsRow><PartsRow><PartNumber>47551-24</PartNumber><PartName>Mirror lens—Right</PartName><PartQuantity>1</PartQuantity></PartsRow><PartsRow><PartNumber>49903-11</PartNumber><PartName>Frame screws</PartName><PartQuantity>2</PartQuantity></PartsRow><PartsRow><PartNumber>48844-13</PartNumber><PartName>Case</PartName><PartQuantity>1</PartQuantity></PartsRow></PartsBody></PartsTable></Parts><Warranty><Para>Slades Sunglasses are warranted to the original purchaser for one full year from date of purchase. Slades will replace or repair any pair of their sunglasses where the defect or damage was not caused by unreasonable or improper use.</Para></Warranty><Distribution><Distributor><Territory>USA</Territory><Company>IPI USA Corp.</Company><Address>50 W 57th Street, New York 10019</Address></Distributor><Distributor><Territory>Canada</Territory><Company>PD Boutiques Canada Inc.</Company><Address>131 Bloor Street W. Suite 200/350, Toronto, Ontario M5S 1R8</Address></Distributor></Distribution><Compliance><Para>This model complies with the requirements of the EC 89/686 directive and the EN 1836 regulation.</Para></Compliance><Notes><Para>Glasses with optical class 1 filters: glasses with filters of this type are most resistant to breakage.</Para><Para>It is recommended that you visit your local sunglass retailer periodically to have the frames adjusted and the screws tightened.</Para></Notes><TroubleshootingLink><SectionLink IdRef = "DAJDIGJH" format = "SectionLink"/></TroubleshootingLink></Model><Model ModelNumber = "146 146 011" Id = "BABGAGCH" Season = "Summer"><Name>XTXR Extreme Sports</Name><Picture><Graphic file = "graphic9.swf" impsize = "1.675in 1.287in" impby = "ref" sideways = "0" impang = "0.000" xoffset = "0.000in" yoffset = "-0.156in" position = "tleft" align = "aoutside" cropped = "0" float = "0" width = "1.385in" height = "1.042in" angle = "0.000" bloffset = "-1.407in" nsoffset = "-1.375in"/></Picture><Description><Para>The XTRX Extreme sports style is the best choice in sunglasses for those who like to take their adventures in the sun to the extreme.</Para></Description><Features><Feature><Para>Light-weight nylon frame</Para></Feature><Feature><Para>Wraparound styling to protect against glare from the sides</Para></Feature><Feature><Para>Exclusive multilayer polarized lenses</Para></Feature><Feature><Para>Adjustable padded earpieces to ensure a snug fit when needed</Para></Feature><Feature><Para>Removable elastic headband</Para></Feature><Feature><Para>Carry pouch/lens cloth included</Para></Feature><Feature><Para>Interchangeable lens inserts sold separately</Para></Feature><Feature><Para>Prescription lenses available through your eye care professional</Para></Feature></Features><Usage><Para>Designed to provide the maximum amount of protection against glare during water, snow, and beach sports. Mechanical superiority makes these glasses suitable for use under the most rigorous outdoor phy
